* Refactored bits for when bashter's run with command line arguments

diff --git a/bashter b/bashter
--- a/bashter
+++ b/bashter
@@ -389,8 +389,6 @@ refresh () {
   for class in $(set | awk -F= "/^CLASS_/"'{ print $1 }'); do
     eval "GLOBAL_$class=$CTIME"
   done
-  runall
-  save
   exit
 }
 
@@ -435,14 +433,6 @@ printDOC(){
 
 
 runonce(){
-  # lock our memfile so we don't run over ourselves
-  exec 9>>$MEMFILE
-  if ! flock -n 9; then
-    # another instance is already running
-    evalall
-    return
-  fi
-
   # Get current time
   CTIME=`date +%s`
 
@@ -455,12 +445,17 @@ runonce(){
     done
     runall
     save
-    evalall
     flock -u 9
     return
-  else
-    evalall
   fi
+  # lock our memfile so we don't run over ourselves
+  exec 9>>$MEMFILE
+  if ! flock -n 9; then
+    # another instance is already running
+    evalall
+    return
+  fi
+  evalall
 
   # Calculate some time since the last time the script ran
   DTIME=$(($CTIME - $GLOBAL_LTIME))
@@ -469,9 +464,17 @@ runonce(){
 # If we have arguments run them as functions
 if [ "$1" ]; then
   [ $1 == "refresh" ] && refresh
+  runonce
   for f in "$@"; do
     # check that the function exists, if not print DOC and bail
-    command -v "F_$f" > /dev/null || printDOC
+    command -v "F_$f" > /dev/null
+    if [ $? != 0 ]; then
+      echo "Command '$f' not found"
+	  printDOC
+      exit
+    fi
+  done
+  for f in "$@"; do
     # run command sending it something
     F_$f 1
   done
